* **Label Encoder -- Encoding target/class info**
* **Ordinal Encoder -- Encoding categorical Features**

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [2]:
data=pd.read_csv('mlfolder/CSV_Files/breast-cancer_modified.csv',na_values=['?'])

In [3]:
data

Class    age menopause tumor-size Inv-nodes Node-caps  \
0    no-recurrence-events  30-39   premeno      30-34       0-2        no   
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
2    no-recurrence-events  40-49   premeno      20-24       0-2        no   
3    no-recurrence-events  60-69      ge40      15-19       0-2        no   
4    no-recurrence-events  40-49   premeno        0-4       0-2        no   
..                    ...    ...       ...        ...       ...       ...   
279     recurrence-events  30-39   premeno      30-34       0-2        no   
280     recurrence-events  30-39   premeno      20-24       0-2        no   
281     recurrence-events  60-69      ge40      20-24       0-2        no   
282     recurrence-events  40-49      ge40      30-34       3-5        no   
283     recurrence-events  50-59      ge40      30-34       3-5        no   

     Deg-malig breast breast-quad irradiat  
0            3   left    left_low       no  
1            2  right    right_up       no  
2            2   left    left_low       no  
3            2  right     left_up       no  
4            2  right   right_low       no  
..         ...    ...         ...      ...  
279          2   left     left_up       no  
280          3   left     left_up      yes  
281          1  right     left_up       no  
282          3   left    left_low       no  
283          3   left    left_low       no  

[284 rows x 10 columns]

**To check if data has null or missing values**

In [4]:
np.sum(data.isna())

/Users/divyamaddipatla/mlfolder/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


Class          0
age            0
menopause      0
tumor-size     0
Inv-nodes      0
Node-caps      8
Deg-malig      0
breast         0
breast-quad    1
irradiat       0
dtype: int64

**Drop/delete the data that has missing values**

In [5]:
datac=data.dropna()

In [6]:
datac

Class    age menopause tumor-size Inv-nodes Node-caps  \
0    no-recurrence-events  30-39   premeno      30-34       0-2        no   
1    no-recurrence-events  40-49   premeno      20-24       0-2        no   
2    no-recurrence-events  40-49   premeno      20-24       0-2        no   
3    no-recurrence-events  60-69      ge40      15-19       0-2        no   
4    no-recurrence-events  40-49   premeno        0-4       0-2        no   
..                    ...    ...       ...        ...       ...       ...   
279     recurrence-events  30-39   premeno      30-34       0-2        no   
280     recurrence-events  30-39   premeno      20-24       0-2        no   
281     recurrence-events  60-69      ge40      20-24       0-2        no   
282     recurrence-events  40-49      ge40      30-34       3-5        no   
283     recurrence-events  50-59      ge40      30-34       3-5        no   

     Deg-malig breast breast-quad irradiat  
0            3   left    left_low       no  
1            2  right    right_up       no  
2            2   left    left_low       no  
3            2  right     left_up       no  
4            2  right   right_low       no  
..         ...    ...         ...      ...  
279          2   left     left_up       no  
280          3   left     left_up      yes  
281          1  right     left_up       no  
282          3   left    left_low       no  
283          3   left    left_low       no  

[275 rows x 10 columns]

In [7]:
np.sum(datac.isna())

/Users/divyamaddipatla/mlfolder/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


Class          0
age            0
menopause      0
tumor-size     0
Inv-nodes      0
Node-caps      0
Deg-malig      0
breast         0
breast-quad    0
irradiat       0
dtype: int64

In [8]:
X=datac.iloc[:,1:]
y=datac.iloc[:,0]

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [10]:
X_train.head()

age menopause tumor-size Inv-nodes Node-caps  Deg-malig breast  \
106  30-39   premeno      40-44       0-2        no          2  right   
158  40-49   premeno      35-39       0-2        no          1   left   
81   60-69      ge40      15-19       0-2        no          2  right   
135  30-39   premeno      40-44       3-5        no          3  right   
157  50-59      ge40      30-34       0-2        no          1  right   

    breast-quad irradiat  
106    right_up       no  
158    left_low       no  
81     left_low       no  
135    right_up      yes  
157     central       no

In [11]:
X_test.head()

age menopause tumor-size Inv-nodes Node-caps  Deg-malig breast  \
118  60-69      ge40      15-19       0-2        no          1   left   
187  40-49   premeno      10-14       0-2        no          2  right   
220  30-39   premeno      30-34       0-2        no          1  right   
154  60-69      ge40      40-44       3-5        no          2  right   
215  50-59      ge40      20-24       0-2        no          2   left   

    breast-quad irradiat  
118   right_low       no  
187     left_up       no  
220     left_up       no  
154     left_up      yes  
215     left_up       no

In [12]:
ordinal_encoder=OrdinalEncoder()
ordinal_encoder.fit(X_train)

OrdinalEncoder()

In [13]:
X_train_encoded=ordinal_encoder.transform(X_train)
X_test_encoded=ordinal_encoder.transform(X_test)

In [14]:
X_train_encoded[1:5,:]

array([[1., 2., 6., 0., 0., 0., 0., 1., 0.],
       [3., 0., 2., 0., 0., 1., 1., 1., 0.],
       [0., 2., 7., 3., 0., 2., 1., 4., 1.],
       [2., 0., 5., 0., 0., 0., 1., 0., 0.]])

In [15]:
X_test_encoded[1:5,:]

array([[1., 2., 1., 0., 0., 1., 1., 2., 0.],
       [0., 2., 5., 0., 0., 0., 1., 2., 0.],
       [3., 0., 7., 3., 0., 1., 1., 2., 1.],
       [2., 0., 3., 0., 0., 1., 0., 2., 0.]])

In [16]:
label_encoder=LabelEncoder()
label_encoder.fit(y_train)
y_train_encoded=label_encoder.transform(y_train)
y_test_encoded=label_encoder.transform(y_test)

In [17]:
y_train_encoded[1:5]

array([0, 0, 0, 0])

In [18]:
y_test_encoded[1:5]

array([0, 1, 0, 1])

In [19]:
model=LogisticRegression()

In [20]:
model.fit(X_train_encoded,y_train_encoded)

LogisticRegression()

In [21]:
predictions=model.predict(X_test_encoded)

In [22]:
accuracy=metrics.accuracy_score(y_test_encoded,predictions)

In [23]:
print('Accuracy: %.2f'%(accuracy*100))

Accuracy: 65.45


In [24]:
ordinal=OrdinalEncoder()
X1=ordinal.fit_transform(data.iloc[:,1:])

In [25]:
X1

array([[0., 2., 5., ..., 0., 1., 0.],
       [1., 2., 3., ..., 1., 4., 0.],
       [1., 2., 3., ..., 0., 1., 0.],
       ...,
       [3., 0., 3., ..., 1., 2., 0.],
       [1., 0., 5., ..., 0., 1., 0.],
       [2., 0., 5., ..., 0., 1., 0.]])

In [26]:
label=LabelEncoder()
y1=label.fit_transform(data.iloc[:,0])

In [27]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
X1_train,X1_test,y1_train,y1_test=train_test_split(X1,y1,test_size=0.2,random_state=0)

In [29]:
model.fit(X1_train,y1_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [30]:
one_hot=OneHotEncoder()
one_hot.fit(X_train)

OneHotEncoder()

In [31]:
X_train_onehot=one_hot.transform(X_train)
X_test_onehot=one_hot.transform(X_test)

In [32]:
X_train_onehot[1:5,:]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 36 stored elements and shape (4, 39)>

In [33]:
X_test_onehot[1:5,:]

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 36 stored elements and shape (4, 39)>

In [34]:
model.fit(X_train_onehot,y_train_encoded)
predictions_onehot=model.predict(X_test_onehot)

In [35]:
accuracy=metrics.accuracy_score(y_test_encoded,predictions_onehot)

In [36]:
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 65.45


In [37]:
datadict={'color':['blue','red','white'],
         'name':['sky','blood','paper']}

In [38]:
df=pd.DataFrame(datadict)

In [39]:
df

color   name
0   blue    sky
1    red  blood
2  white  paper

In [40]:
enc=OneHotEncoder(sparse_output=False)

In [41]:
encoded=enc.fit_transform(df)

In [42]:
encoded

array([[1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.]])

**sparse_output=False --> the encoder will return a dense NumPy array instead of a sparse matrix.**

In [44]:
enc.categories_

[array(['blue', 'red', 'white'], dtype=object),
 array(['blood', 'paper', 'sky'], dtype=object)]