In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn import preprocessing

In [2]:
d=datasets.load_iris()

In [3]:
d.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,y_train,y_test=train_test_split(d.data,d.target,test_size=0.2,random_state=4,stratify=d.target)

In [6]:
X_train.shape

(120, 4)

In [7]:
X_test.shape

(30, 4)

In [8]:
y_train.shape

(120,)

In [9]:
y_test.shape

(30,)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_predictions=knn.predict(X_test)

In [11]:
from sklearn import metrics

In [12]:
print("Accuracy: ",metrics.accuracy_score(y_test,y_predictions))

Accuracy:  0.9333333333333333


In [13]:
print(metrics.classification_report(y_test,y_predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.80      0.89        10
           2       0.83      1.00      0.91        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [14]:
print(metrics.confusion_matrix(y_test,y_predictions))

[[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]


In [15]:
y_test

array([1, 0, 1, 1, 2, 0, 1, 0, 0, 1, 2, 0, 2, 1, 0, 2, 0, 2, 0, 2, 2, 0,
       1, 2, 2, 1, 0, 1, 2, 1])

In [16]:
knn=KNeighborsClassifier(n_neighbors=10)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
print("Accoracy: ",metrics.accuracy_score(y_test,y_pred))

Accoracy:  0.9666666666666667


In [17]:
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
print("Accoracy: ",metrics.accuracy_score(y_test,y_pred))

Accoracy:  0.9333333333333333
