<a href="https://colab.research.google.com/github/divyam9876/ML/blob/main/MultipleRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving wine_small.csv to wine_small.csv


In [ ]:
wineData=pd.read_csv("wine_small.csv")

In [ ]:
wineData

sulphates  alcohol  quality
0          0.56      9.4        5
1          0.68      9.8        5
2          0.65      9.8        5
3          0.58      9.8        6
4          0.56      9.4        5
...         ...      ...      ...
1594       0.58     10.5        5
1595       0.76     11.2        6
1596       0.75     11.0        6
1597       0.71     10.2        5
1598       0.66     11.0        6

[1599 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = wineData.iloc[:,:-1]
y=wineData.iloc[:,-1]

In [ ]:
X

sulphates  alcohol
0          0.56      9.4
1          0.68      9.8
2          0.65      9.8
3          0.58      9.8
4          0.56      9.4
...         ...      ...
1594       0.58     10.5
1595       0.76     11.2
1596       0.75     11.0
1597       0.71     10.2
1598       0.66     11.0

[1599 rows x 2 columns]

In [ ]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [ ]:
Xtrain,Xtest,yTrain,yTest = train_test_split(X,y,random_state=42,test_size=0.25)

In [ ]:
yTest

803     6
124     5
350     6
682     5
1326    6
       ..
1565    6
327     5
254     6
322     5
1160    7
Name: quality, Length: 400, dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
reg=LinearRegression()

In [ ]:
reg.fit(Xtrain,yTrain)

LinearRegression()

In [ ]:
reg.intercept_

1.3043564763577624

In [ ]:
reg.coef_

array([0.8723369 , 0.35959789])

In [ ]:
prediction=reg.predict(Xtest)

In [ ]:
newData=pd.DataFrame([[.58,11]])

In [ ]:
reg.predict(newData)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.76588861])

In [ ]:
reg.score(Xtest,yTest)

0.2582084585479647

In [ ]:
reg.score(Xtrain,yTrain)

0.27184222601056107

**reg.score -- gives r^2 **

**Cigarettes**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cigarettes.csv to cigarettes.csv


In [ ]:
data2=pd.read_csv("cigarettes.csv")

In [ ]:
X2=data2.iloc[:,1:-1]
Y2=data2.iloc[:,-1]

In [ ]:
X2.head()

Tar (mg)  Nicotine (mg)  Weight (g)
0      14.1           0.86      0.9853
1      16.0           1.06      1.0938
2      29.8           2.03      1.1650
3       8.0           0.67      0.9280
4       4.1           0.40      0.9462

In [ ]:
Y2.head()

0    13.6
1    16.6
2    23.5
3    10.2
4     5.4
Name: CO content (mg), dtype: float64

In [ ]:
model2=LinearRegression()
model2.fit(X2,Y2)

LinearRegression()

In [ ]:
a=model2.intercept_
b=model2.coef_

In [ ]:
a

3.2021900191923365

In [ ]:
b

array([ 0.96257386, -2.63166111, -0.13048185])

In [ ]:
model2.score(X2,Y2)

0.9185893479475057

In [ ]:
prediction2=model2.predict([[15,1.23,.8885]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [ ]:
prediction2

array([14.28792158])