In [11]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [3]:
iris=load_iris()
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=4)

In [5]:
pipeline1=Pipeline([('scaler',StandardScaler()),('pca',PCA(n_components=2)),('clf',DecisionTreeClassifier())])

In [6]:
pipeline1.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('clf', DecisionTreeClassifier())])

In [7]:
pipeline1.score(X_test,y_test)

0.8666666666666667

In [8]:
pipeline1.predict(X_test)

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 2,
       2, 0, 0, 0, 0, 0, 0, 2])

In [9]:
y_test

array([2, 0, 2, 2, 2, 1, 1, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2])

In [10]:
pipeline2 = Pipeline([('scaler', StandardScaler()),('pca', PCA(n_components=2)),('clf', SVC(C=1000))])

In [11]:
pipeline2.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=2)),
                ('clf', SVC(C=1000))])

In [12]:
pipeline2.score(X_test,y_test)

0.9333333333333333

In [13]:
pipeline2.predict(X_test)

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       2, 0, 0, 0, 0, 0, 0, 2])

In [1]:
import pandas as pd
import numpy as np

In [2]:
titanic=pd.read_csv('mlfolder/CSV_Files/Titanic_mixed.csv')

In [3]:
titanic.head()

survived  pclass     sex   age     fare embarked
0         0       3    male  22.0   7.2500        S
1         1       1  female  38.0  71.2833        C
2         1       3  female  26.0   7.9250        S
3         1       1  female  35.0  53.1000        S
4         0       3    male  35.0   8.0500        S

In [4]:
titanic.shape

(891, 6)

In [5]:
X=titanic.drop('survived',axis=1)
y=titanic['survived']

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [7]:
np.random.seed(10)

In [9]:
numeric_features=['age','fare']
numeric_transformer=Pipeline(steps=[('imputer',SimpleImputer(strategy='median')),('scaler',StandardScaler())])
categorical_features=['sex','embarked','pclass']
categorical_transformer=OneHotEncoder(handle_unknown='ignore')

preprocessor=ColumnTransformer(transformers=[
    ('num',numeric_transformer,numeric_features),
    ('cat',categorical_transformer,categorical_features)
])

clf=Pipeline(steps=[('preprocessor',preprocessor),('classifier',LogisticRegression())])

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [16]:
clf.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'fare']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['sex', 'embarked',
                                                   'pclass'])])),
                ('classifier', LogisticRegression())])

In [17]:
print("Model score: %.3f" % clf.score(X_test,y_test))

Model score: 0.799
