In [1]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns

**Standard Scaler**
* x_dash = mean of x
* σ = standard deviation
* $x'=(x-x_dash)/σ$
* makes mean 0 of each feature and variance 1
* SVM,Logistic Regression
* distort relative shapes

**Min Max Scaler**
* $x'=(x-min(x))/(max(x)-min(x)$
* scales all data features to an interval[0,1]
* doesn't distort data

In [2]:
scaler=preprocessing.StandardScaler()
# scaled_df=scaler.fit_transform(data)

In [3]:
# scaler1=preprocessing.MinMaxScaler()

In [4]:
def add2(x):
    return x+2

In [5]:
add2(21)

23

In [6]:
x1=np.array([2,3,4,8])
x2=np.array([33,12,20,30])

**Create a DataFrame from the Arrays**

In [7]:
df=pd.DataFrame({'x1':x1,'x2':x2})

In [8]:
df

x1  x2
0   2  33
1   3  12
2   4  20
3   8  30

In [9]:
add2(x1)

array([ 4,  5,  6, 10])

In [10]:
add2(df)

x1  x2
0   4  35
1   5  14
2   6  22
3  10  32

In [23]:
def minMaxScaler(x):
    # mini=np.min(x)
    mini=min(x)
    maxi=np.max(x)
    x_new=(x-mini)/(maxi-mini)
    return x_new

In [24]:
X=np.array([2,3,4,8,10,20])


In [25]:
minMaxScaler(X)

array([0.        , 0.05555556, 0.11111111, 0.33333333, 0.44444444,
       1.        ])

In [26]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [15]:
scaler.fit_transform(X.reshape(-1,1))

array([[0.        ],
       [0.05555556],
       [0.11111111],
       [0.33333333],
       [0.44444444],
       [1.        ]])

In [16]:
a=minMaxScaler(X)
b=scaler.fit_transform(X.reshape(-1,1))

In [17]:
b.ravel()

array([0.        , 0.05555556, 0.11111111, 0.33333333, 0.44444444,
       1.        ])

In [18]:
a-b.ravel()

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -5.55111512e-17,  0.00000000e+00])

In [19]:
minMaxScaler(df)

x1        x2
0  0.000000  1.000000
1  0.032258  0.322581
2  0.064516  0.580645
3  0.193548  0.903226

In [20]:
scaler.fit_transform(df)

array([[0.        , 1.        ],
       [0.16666667, 0.        ],
       [0.33333333, 0.38095238],
       [1.        , 0.85714286]])